---
title: "Exercise_1"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Initialize

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins) #load data
library(ggthemes)
```

# Import Data

```{r}
df <- 
  palmerpenguins::penguins
df
```

```{r}
nrow(df)

```

```{r}
isTRUE("bill_depth_mm" %in% colnames(df))

```

```{r}
ggplot(
  data = df,
  mapping = 
    aes(
      x = bill_length_mm,
      y = bill_depth_mm
    )
  )+
    geom_point(
      aes(
        color = species, 
        shape = species
        ),
      na.rm = TRUE
    ) +
    geom_smooth(
      method = "lm"
    ) +
    labs(
      title = "Bill length and Bill depth",
      subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
      caption = "Data come from the palmerpenguins package",
      x = "Bill length (mm)", 
      y = "Bill Depth (mm)",
      color = "Species", 
      shape = "Species"
    ) +
    scale_color_colorblind()

```

```{r}
ggplot(
  data = df,
  mapping = 
    aes(
      x = bill_depth_mm,
      y = species
    )
) +
  geom_point(
    na.rm = TRUE
  )
```

```{r}
ggplot(
  data = penguins,
  mapping = 
    aes(
      x = flipper_length_mm, 
      y = body_mass_g
      )
) +
  geom_point(
    aes(
      color = bill_depth_mm
      )
    ) +
  geom_smooth(
    method = "gam"
    ) +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", 
    y = "Body mass (g)",
    
  ) 
```

```{r}
ggplot(
  data = df,
  mapping = 
    aes(
      x = flipper_length_mm, 
      y = body_mass_g, 
      color = island
      )
) +
  geom_point() +
  geom_smooth(se = FALSE)
```

```{r}
ggplot(
  data = penguins,
  mapping = 
    aes(
      x = flipper_length_mm, 
      y = body_mass_g
      )
) +
  geom_point() +
  geom_smooth()

ggplot() +
  geom_point(
    data = penguins,
    mapping = 
      aes(
        x = flipper_length_mm, 
        y = body_mass_g
        )
  ) +
  geom_smooth(
    data = penguins,
    mapping = 
      aes(
        x = flipper_length_mm, 
        y = body_mass_g
        )
  )
```

```{r}
ggplot(
  data = df,
  mapping = 
    aes(
      x = species
    )
) +
  geom_bar()
```

```{r}
ggplot(
  data = df,
  mapping = 
    aes(
      y = species
    )
) +
  geom_bar()
```

```{r}
ggplot(
  penguins, 
  aes(
    x = species
    )
  ) +
  geom_bar(
    color = "red"
    )

ggplot(
  penguins, 
  aes(
    x = species
    )
  ) +
  geom_bar(
    fill = "red"
    )
```

```{r}
ggplot(
  df, 
  aes(
    x = species,
    y = body_mass_g
    )
  ) +
  geom_boxplot()
```

```{r}
ggplot(
  df, 
  aes(
    x = body_mass_g, 
    color = species
    )
  ) +
  geom_density(
    linewidth = 0.75
    )
```

```{r}
ggplot(
  df, 
  aes(
    x = body_mass_g, 
    color = species, 
    fill = species
    )
  ) +
  geom_density(
    alpha = 0.5
    )
```

```{r}
ggplot(
  df, 
  aes(
    x = island, 
    fill = species
    )
  ) +
  geom_bar()
```

```{r}
ggplot(
  df, 
  aes(
    x = island, 
    fill = species)
  ) +
  geom_bar(
    position = "fill"
    )
```

```{r}
ggplot(
  df, 
  aes(
    x = flipper_length_mm, 
    y = body_mass_g
    )
  ) +
  geom_point(
    aes(
      color = species, 
      shape = island
      )
    )

```

```{r}
ggplot(
  df, 
  aes(
    x = flipper_length_mm, 
    y = body_mass_g)
  ) +
  geom_point(
    aes(
      color = species, 
      shape = species
      )
    ) +
  facet_wrap(~island)
```

```{r}
df <- ggplot2::mpg
is.numeric(df)
```

```{r}
ggplot(
  df,
  aes(
    x = hwy,
    y = displ,
    color = year,
    size = manufacturer,
    shape = class
  )
) +
  geom_point()
```

```{r}
ggplot(
  df,
  aes(
    x = hwy,
    y = displ,
    linewidth = model
  )
) +
  geom_point(
    
  )
```

```{r}
ggplot(
  data = penguins,
  mapping = 
    aes(
      x = bill_length_mm, 
      y = bill_depth_mm, 
      color = species, 
      shape = species
  )
) +
  geom_point() 
```

```{r}
ggplot(
  penguins, 
  aes(
    x = island, 
    fill = species
    )
  ) +
  geom_bar(
    position = "fill"
    )

ggplot(
  penguins, 
  aes(
    x = species, 
    fill = island
    )
  ) +
  geom_bar(
    position = "fill")

```
